name: Oracle Capacity Retry

on:
  workflow_dispatch:

  schedule:
    - cron: "*/15 * * * *"
jobs:
  retry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install oci requests

      - name: Run Oracle Retry Bot
        env:
          OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}

          COMPARTMENT_OCID: ${{ secrets.COMPARTMENT_OCID }}
          SUBNET_OCID: ${{ secrets.SUBNET_OCID }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

          IMAGE_OCID: ${{ secrets.IMAGE_OCID }}

          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

        run: |
          python retry.py
